"""Regenerate js/colormaps.js from matplotlib (256 RGB entries per map)."""
from pathlib import Path

import matplotlib
import numpy as np
from matplotlib import colormaps

NAMES = ['magma', 'viridis', 'inferno', 'plasma', 'cividis', 'turbo', 'gray', 'coolwarm']
OUT = Path(__file__).resolve().parents[1] / 'js' / 'colormaps.js'

lines = [f'// Generated by tools/make_colormaps.py from matplotlib {matplotlib.__version__}.',
         '// Each entry is 256 RGB triplets as hex.', 'export const COLORMAPS = {']
for name in NAMES:
    rgb = np.round(colormaps[name](np.linspace(0, 1, 256))[:, :3] * 255).astype(np.uint8)
    lines.append(f"  {name}: '{rgb.tobytes().hex()}',")
lines.append('};')
OUT.write_text('\n'.join(lines) + '\n')
print('wrote', OUT)
